### ISSUE TITLE
GS 308E: Lack of traffic sensor data

### ISSUE THREAD

**Issue by estozehn** [ckarrie/ha-netgear-plus#13]
Hi @ckarrie, thanks again for this integration. I tried to set it up with my Netgear GS 308 E (no P), could log in fine, get some basic information like IP, name and such, but no updates on traffic on port sensors. Updates seem to be an issue, as I changed the name of the switch, which wasn't reflected up until a restart of Home Assistant. No sensor data even after restart.
Switch Firmware is: V1.00.11EN
If you finde the time and are in the mood for some netgearing...
Thanks and all the best!

**Comment by williamwwlr** [comment]
Bonjour idem de mon coté Pas de possibilité d'avoir des stats 
Peut tu corriger ton code ou l'adapter pour ce model 
Merci et bonne chance !

**Comment by mapo-89** [comment]
For me it worked to change 
PORT_STATISTICS_URL_TMPL = 'http://{ip}/port_statistics.htm' and change the Bootloader to ['V0.00.00']
in the _init_.py in the gs108e folder

**Comment by estozehn** [comment]
Hi @mapo-89 , unfortunately it doesn't work for me, but I might be too stupid and overlook something. Can you elaborate where exactly you changed the entries?
After restart it says setup failed at the integration.

> @estozehn For me it worked to change PORT_STATISTICS_URL_TMPL = 'http://{ip}/port_statistics.htm' and change the Bootloader to ['V0.00.00'] in the _init_.py in the gs108e folder

**Comment by williamwwlr** [comment]
Bonjour peut tu nous en dire plus sur quelle fichier a modifier ou a la limite rendre compatible ton code merci

**Comment by ckarrie** [comment]
Hi, the GS308E firmware compared to the G108 is different. I finally owned a GS308E so there will be an update soon

**Comment by williamwwlr** [comment]
Si besoin je veut bien être testeur

**Comment by williamwwlr** [comment]
Des news ?

**Comment by ckarrie** [comment]
> Des news ?

I'm working in it. The GS308EP I owned was damaged. New one works fine.

**Comment by ckarrie** [comment]
Hi @williamwwlr @mapo-89 @mapo-89 @el97 could you check out the https://github.com/ckarrie/ckw-ha-gs108e/tree/gs3x-branch if the traffic sensors works for your GS3xx devices? It seems for me, the calculated TX/RX speed is wrong (factor 10?). Any help is appreciated.

**Comment by ckarrie** [comment]
Oops, mentioned the wrong person. @estozehn should be the man

**Comment by estozehn** [comment]
Hi @ckarrie, receiving data, awesome. I'll do some checks and testing and let you know.
Thanks for sticking to it. This is great!

**Comment by foxey** [comment]
@estozehn can we close this issue?

**Comment by estozehn** [comment]
@foxey Yes, I'd say so.

**Comment by estozehn** [comment]
all looks good

**Comment by foxey** [comment]
Great, thanks!
