### ISSUE TITLE
Image missing in HA

### ISSUE THREAD

**Issue by gdi0110** [ckarrie/ha-netgear-plus#22]
It appears the custom integration does not have an entry in the [HA Brands](https://github.com/home-assistant/brands) repo.

The images could made to show generic Netgear pngs, same as this other [Netgear custome integration](https://github.com/home-assistant/brands/pull/2669/files).

If the above images are okay, I can change this [HA Brands PR #5758 from Draft to Review](https://github.com/home-assistant/brands/pull/5758)?

**Comment by ckarrie** [comment]
Yeah thank you, Image is not perfect but better than nothing :-)

Thank you!

**Comment by foxey** [comment]
Fixed in https://github.com/home-assistant/brands/pull/5909
