### ISSUE TITLE
Add topics in the "About" section of the repository (HACS CI issue)

### ISSUE THREAD

**Issue by foxey** [ckarrie/ha-netgear-plus#35]
### System Health details

NA

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ckarrie/ha-netgear-plus/issues?q=is%3Aissue+label%3A%22Bug%22+).

### Describe the issue

Can you please add these "topics" in the "About" section of the repository?
Topics are mandatory for HACS and currently blocking further merging of pull requests.
I added these to my forked repository:
networking, integration, home-assistant, homeassistant, netgear, custom-component

I would have done it myself, but I can't edit the repo's meta data.

### Reproduction steps

1. Try merge a pull request

### Debug logs

```text
Error:  <Validation topics> failed:  The repository has no valid topics (More info: https://hacs.xyz/docs/publish/include#check-repository )
```

**Comment by ckarrie** [comment]
Hi Foxey, thanks for your contributions!
I added these topics, if you need more, tell me.

**Comment by foxey** [comment]
All good now!
