### ISSUE TITLE
update from 0.6.1 to 0.6.2 and up

### ISSUE THREAD

**Issue by Megachip** [ckarrie/ha-netgear-plus#37]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1453
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 116.7 GB
disk_used | 35.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), File editor (5.7.0), Node-RED (16.0.2), Log Viewer (0.17.1), Portainer (2.0.0), SQLite Web (4.1.0), ledfx (d7e3146), Samba share (12.2.0), ESPHome (2024.8.3), Mosquitto broker (6.4.1), Ring-MQTT with Video Streaming (5.7.1), Matter Server (6.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 3
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 17, 2024 at 3:55 PM
-- | --
current_recorder_run | October 22, 2024 at 9:57 PM
estimated_db_size | 3674.41 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 0 / 2
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ckarrie/ha-netgear-plus/issues?q=is%3Aissue+label%3A%22Bug%22+).

### Describe the issue

it seems through the renaming upgrade didn't work proper. Ill guess it installing the newer version as a 2nd instance (folder), but only the first will be used. A complete uninstall and reinstall seems solve this issue, but maybe this should be mentioned in update logs?

### Reproduction steps

1. Update
2. Reboot
3. Be confused
...

### Debug logs

```text
%
```

**Comment by foxey** [comment]
Thanks for the feedback! I assume that the renaming of the repository is the root cause of this problem, but I cannot test it as HACS doesn't let me install v0.6.1 anymore. I'll add a note in the readme to mitigate your point "3. Be confused" for others.

**Comment by foxey** [comment]
Warning added to most recent release (v0.6.5)
